name: Multi-Stage Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Stage
        run: echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: build  # Runs only after 'build' job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Stage
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Runs only after 'test' job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Stage
        run: echo "Deploying the application..."
